name: "build-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run dist
